chore: update esbuild (#361)
This change updates esbuild to latest version. The
[esbuild-jest](https://github.com/aelbore/esbuild-jest) does not work
with the latest esbuild by the error:

```
ERROR: Transforming JavaScript decorators to the configured target environment ("es2018") is not supported yet
``` 

The esbuild-jest proejct has been no longer maintained and replace it
with the [ts-jest](https://github.com/kulshekhar/ts-jest).